# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c28f8ee066461780953c5849daf43a22378fb3041173c084e581f9f337ac7790d09d8b060a87cde5a367df9707278afa7a680ebaf62f14234273021f69dd7312

test:
  secret_key_base: 5c632566f4485d097096cfc2ba03c46740f210230d3f38fe28a775999c06a9ac5a8c9542363f209c8ef54cd807e933e11b680bff1a0d3bfaf40da839f6a8701e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
